### ISSUE TITLE
Control not properly working with "First to respond" way

### ISSUE THREAD

**Issue by MarcoMarconetti** [tcorcor1/group-approval-viewer-D365-pcf#1]
Hello Ty,
great!
I' don't know if it's an issue but if I use the "First to respond" way in Power Automate "Create an Approval" action, in this Control I can only see the last Response. So, for example, if I reject the record, then the user changes some values and re-sends it for approval, and finally the approver approves the record, the system will show only the last action. Is it possible to check?

**Comment by tcorcor1** [comment]
Hi Marco,

This is by design. The control is bound to the lookup on the record and just displays data down that relationship (approvals > approval requests > approval responses). In your scenario it sounds like your Flow is creating a NEW approval instance and replacing the lookup value hence why you only see the most recent. 

At this time the control is not designed to support multiple approvals instances related to a record but you have given me something to think about. Thanks for submitting the comment!
